<!DOCTYPE html>
<html lang="pt-br">
<head>
  <title><?= APPNAME ?></title>
  <meta charset="utf-8">
  <meta name="author" content="<?= AUTHOR ?>">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="<?= CSS ?>bootstrap.min.css">
  <script src="<?= JS ?>jquery-3.5.1.slim.min.js"></script>
  <script src="<?= JS ?>popper.min.js"></script>
  <script src="<?= JS ?>bootstrap.min.js"></script>
</head>
<body onload="onload()">

<?php include_once("navbar.phtml") ?>

<div class="container">
  <div class="card border border-secondary">
    <div class="card-header bg-secondary">
      <h5 class="text-light mb-0">Pesquisa</h5>
    </div>
    <div class="card-body">
      <div class="row">
        <div class="col-3">
          <input type="text" name="cep" value="97020-10" id="cep" class="form-control" placeholder="Digite o CEP">
        </div>
        <div class="col-2">
          <button class="btn btn-success" onclick="buscarCEP()">Buscar</button>
        </div>
      </div>
    </div>

    <div class="card-body pt-0" id="show-message">
    </div>

    <table class="table">
      <tr>
        <th>CEP</th>
        <th>Logradouro</th>
        <th>Bairro</th>
        <th>Localidade/UF</th>
        <th>Complemento</th>
      </tr>
    </table>
  </div>
</div>

<script type="text/javascript">
  const WWW = "<?= WWW ?>";
  console.log(WWW);
  let input;

  function onload() {
    input = document.getElementById('cep');
  }

  function showMsg(msg) {
    if (msg.length > 0) {
      msg = '<div class="table-danger p-3 rounded border border-danger shadow-sm"><h6 class="text-danger mb-0" id="msg">'
        + msg
        + '</h6></div>';
      document.getElementById("show-message").insertAdjacentHTML('afterbegin', msg);
    }
  }

  function buscarCEP() {
    let cep = input.value;
    cep = cep.replace(/[^0-9 ]/g, "");

    if (cep.length !== 8) {
      showMsg("CEP inválido. O campo CEP precisa ter 8 digitos");

      return;
    }

    console.log( httpGet("http://viacep.com.br/ws/01001000/xml/") )
  }

  function httpGet(url)
  {
    var xmlHttp = new XMLHttpRequest();
    xmlHttp.open( "GET", url, false );
    xmlHttp.send( null );
    return xmlHttp.responseText;
  }
</script>

</body>
</html>
