<head>
    <title><?= APPNAME ?></title>
    <meta charset="utf-8">
    <meta name="author" content="<?= AUTHOR ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="<?= CSS ?>bootstrap.min.css">
    <link rel="stylesheet" href="<?= CSS ?>custom.css">
    <!--<script src="<?= JS ?>jquery-3.5.1.slim.min.js"></script>-->
    <!--<script src="<?= JS ?>popper.min.js"></script>-->
    <script src="<?= JS ?>bootstrap.min.js"></script>
    <script src="<?= JS ?>main.js"></script>
</head>
