<nav class="navbar navbar-expand-lg navbar-light bg-light shadow-sm mb-3">
  <a class="navbar-brand" href="#"> <?= APPNAME ?> </a>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto"></ul>
    <button id="modalTrigger" class="btn btn-primary">
      <span class="material-icons">contact_page</span>
    </button>
  </div>
</nav>

<div id="modalSobre" class="modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Informações</h5>
        <button type="button" class="close" data-dismiss="modal">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Desenvolvedor: <?= AUTHOR ?></p>
        <p>Contato: <?= MAILTO ?></p>
      </div>
    </div>
  </div>
</div>

<style>
    .modal {
        display: none;
        position: fixed;
        z-index: 1;
        left: 0;
        top: 0;
        width: 100%;
        height: 100%;
        overflow: auto;
        background-color: rgb(0,0,0);
        background-color: rgba(0,0,0,0.4);
    }
</style>

<script>
  let modal = document.getElementById("modalSobre");
  let btn = document.getElementById("modalTrigger");
  let span = document.getElementsByClassName("close")[0];

  btn.onclick = function() {
    modal.style.display = "block";
  }

  span.onclick = function() {
    modal.style.display = "none";
  }

  window.onclick = function(event) {
    if (event.target === modal) {
      modal.style.display = "none";
    }
  }
</script>
