<nav class="navbar navbar-expand-lg navbar-light bg-light shadow-sm mb-3">
  <a class="navbar-brand" href="#"> <?= APPNAME ?> </a>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto"></ul>
    <button class="btn btn-primary" data-toggle="modal" data-target="#modalSobre">
      <span class="material-icons">contact_page</span>
    </button>
  </div>
</nav>

<div id="modalSobre" class="modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Informações</h5>
        <button type="button" class="close" data-dismiss="modal">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Desenvolvedor: <?= AUTHOR ?></p>
        <p>Contato: <?= MAILTO ?></p>
      </div>
    </div>
  </div>
</div>
